; Hytech VCF PlatformIO configuration file.
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[common]
lib_deps_shared =
    https://github.com/hytech-racing/shared_firmware_types.git#5e98919bd05951dee3daa3a42a5f73ea3539f093
    https://github.com/hytech-racing/shared_firmware_systems.git#af96a631bd76ac4da2084c6fa4faa62ca1bac9d1
    https://github.com/hytech-racing/HT_SCHED.git#c13cff762c59dd82a8c273e3e98fd1a80622656d
    Embedded Template Library@^20.39.4
    nanopb/Nanopb@0.4.91

[hw_common]
lib_deps =
    https://github.com/hytech-racing/HT_CAN/releases/download/264/can_lib.tar.gz
    https://github.com/hytech-racing/HT_proto/releases/download/2026-06-14T06_30_48/hytech_msgs_pb_lib.tar.gz
    https://github.com/hytech-racing/shared_firmware_interfaces.git#2c81ce7c0a8ef105241394d336166c075ca0d1ad
    https://github.com/KSU-MS/pio-git-hash-gen#7998b5b3f8a2464209b0e73338717998bcf511ee
    blemasle/MCP23017@^2.0.0
    arkhipenko/TaskScheduler@^3.8.5

[teensy_common]
platform        = teensy@5.2.0
board           = teensy41
framework       = arduino
monitor_speed   = 115200
upload_protocol = teensy-cli
build_unflags   = -std=gnu++11
build_flags     =
    -std=c++17
    -D TEENSY_OPT_SMALLEST_CODE
check_tool      = clangtidy
check_severity  = medium, high
check_flags     =
    clangtidy: --config-file=./.clang-tidy
check_src_filters =
    +<include/*>
    +<lib/*>
    +<src/*>
    -<src/old_main.cpp>
test_ignore     =
    test_interfaces
    test_systems

[platformio]
default_envs = teensy41


; Teensy41 Environment. This environment is the primary environment for uploading code to the car.
; * Build to verify the on-car software.
; * UPLOAD to compile and upload on-car software.
; * TEST is not yet configured.
[env:teensy41]
extends          = teensy_common
test_framework   = googletest
build_src_filter =
    +<*.cpp>
    -<test_ethernet_main.cpp>
    -<test_adcs.cpp>
    -<test_pedals_main.cpp>
    -<test_can.cpp>
    -<test_orbis.cpp>
lib_deps =
    ${common.lib_deps_shared}
    ${hw_common.lib_deps}
    https://github.com/adafruit/Adafruit_NeoPixel.git


; Test Systems Environment. This is only for compiling and uploading the hardware-abstracted code.
; * BUILD to verify the SYSTEMS compile.
; * DO NOT UPLOAD. This is a test-only environment.
; * TEST to run all unit tests in test_systems on the existing system code.
[env:test_systems_env]
platform         = native
test_framework   = googletest
build_unflags    = -std=gnu++11
build_flags      =
    -std=c++17
    -g
    -D TESTING_SYSTEMS
build_src_filter =
    -<**/*.cpp>
    +<../test/test_systems/main.cpp>
test_ignore      =
    test_interfaces*
lib_deps         =
    ${common.lib_deps_shared}
    google/googletest@^1.15.2

[env:test_orbis]
extends          = teensy_common
build_src_filter =
    +<*.cpp>
    +<test_orbis.cpp>
    -<test_ethernet_main.cpp>
    -<test_pedals_main.cpp>
    -<test_adcs.cpp>
    -<test_can.cpp>
    -<main.cpp>
lib_deps =
    ${common.lib_deps_shared}
    ${hw_common.lib_deps}
    https://github.com/adafruit/Adafruit_NeoPixel.git

[env:test_adcs]
extends          = teensy_common
build_src_filter =
    +<*.cpp>
    -<test_ethernet_main.cpp>
    -<test_pedals_main.cpp>
    -<test_orbis.cpp>
    -<main.cpp>
    -<test_can.cpp>
lib_deps =
    ${common.lib_deps_shared}
    ${hw_common.lib_deps}

[env:test_can]
extends          = teensy_common
build_src_filter =
    +<*.cpp>
    -<test_ethernet_main.cpp>
    -<test_pedals_main.cpp>
    -<main.cpp>
    -<test_adcs.cpp>
    -<test_orbis.cpp>
lib_deps =
    ${common.lib_deps_shared}
    ${hw_common.lib_deps}

[env:test_pedals_env]
extends          = teensy_common
test_framework   = googletest
build_src_filter =
    +<*.cpp>
    -<test_ethernet_main.cpp>
    -<test_adcs.cpp>
    -<test_orbis.cpp>
    -<main.cpp>
    -<test_can.cpp>
lib_deps =
    ${common.lib_deps_shared}
    ${hw_common.lib_deps}