; 2025 Hytech CCU PlatformIO configuration file.
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[common]
lib_deps_shared =
    https://github.com/hytech-racing/shared_firmware_types.git#5e98919bd05951dee3daa3a42a5f73ea3539f093
    https://github.com/hytech-racing/shared_firmware_systems.git#af96a631bd76ac4da2084c6fa4faa62ca1bac9d1
    https://github.com/hytech-racing/HT_SCHED.git#c13cff762c59dd82a8c273e3e98fd1a80622656d
    Embedded Template Library@^20.39.4
    nanopb/Nanopb@0.4.91

[hw_common]
lib_deps =
    https://github.com/hytech-racing/HT_CAN/releases/download/264/can_lib.tar.gz
    https://github.com/hytech-racing/HT_proto/releases/download/2026-06-14T06_30_48/hytech_msgs_pb_lib.tar.gz
    https://github.com/hytech-racing/shared_firmware_interfaces.git#c3d3f409ca031917aa80e316822f931a1a9c17aa
    https://github.com/KSU-MS/pio-git-hash-gen#7998b5b3f8a2464209b0e73338717998bcf511ee
    blemasle/MCP23017@^2.0.0
    arkhipenko/TaskScheduler@^3.8.5

[teensy_common]
platform        = teensy
board           = teensy41
framework       = arduino
monitor_speed   = 115200
upload_protocol = teensy-cli
build_unflags   = -std=gnu++11
build_flags     =
    -std=c++17
    -D TEENSY_OPT_SMALLEST_CODE
check_tool      = clangtidy
check_severity  = medium, high
check_flags     =
    clangtidy: --config-file=./.clang-tidy
check_src_filters =
    +<include/*>
    +<lib/*>
    +<src/*>
test_ignore     = test*

[platformio]
default_envs = teensy41


[env:teensy41]
extends          = teensy_common
lib_ldf_mode     = deep+
build_src_filter =
    +<**/*.cpp>
check_src_filters =
    +<include/*>
    +<lib/*>
    +<src/*>
lib_deps =
    ${common.lib_deps_shared}
    ${hw_common.lib_deps}
    https://github.com/vindar/ILI9341_T4.git
    https://github.com/adafruit/Adafruit_ILI9341.git
    SPI

[env:test_systems_env]
platform = native
test_framework = googletest
build_unflags    = -std=gnu++11
build_flags      =
    -std=c++17
    -g
    -D TESTING_SYSTEMS
    -Ilib/interfaces/include
build_src_filter =
    -<main.cpp>
    +<../test/test_maincharge.cpp>
lib_ignore       = interfaces
lib_deps         =
    ${common.lib_deps_shared}
    google/googletest@^1.15.2