name: Generate and Release

on:
  push:
    branches:
      - master

jobs:
  build-lib:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [23.11]
    steps:
      - uses: cachix/install-nix-action@v23
      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v9
      
      - name: Get current date and time
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H_%M_%S')"

      - uses: actions/checkout@v4
        with:
          repository: hytech-racing/HT_proto
          ref: refs/heads/master
          
      - run: nix run .#nanopb-runner -- ${{ steps.date.outputs.date }}
      
      - name: create release artifact
        run: |
          mkdir -p hytech_msgs_pb_lib
          mv *.pb.* hytech_msgs_pb_lib
          mv hytech_msgs_version.h hytech_msgs_pb_lib
          echo -e "{\n\"name\": \"hytech_msgs_pb_lib\",\n\"version\": \"1.${{ github.run_number }}.0\"\n}" >> hytech_msgs_pb_lib/library.json
          tar -czvf hytech_msgs_pb_lib.tar.gz hytech_msgs_pb_lib

      - name: Setup protobuf tools for python library build
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler python3-protobuf

      - name: Build python protobuf library
        run: |
          mkdir -p python_hytech_msgs_proto_lib
          protoc -I=./proto --python_out=python_hytech_msgs_proto_lib proto/base_msgs.proto proto/hytech_msgs.proto proto/dv_msgs.proto
          tar -czvf python_hytech_msgs_proto_lib.tar.gz python_hytech_msgs_proto_lib
      
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.date.outputs.date }}
          files: |
            hytech_msgs_pb_lib.tar.gz
            python_hytech_msgs_proto_lib.tar.gz 
            ./proto/base_msgs.proto
            ./proto/hytech_msgs.proto
            ./proto/dv_msgs.proto

      - name: Save tag name to file
        run: echo ${{ steps.date.outputs.date }} > tag_name.txt

      - name: Upload tag_name as artifact
        uses: actions/upload-artifact@v4
        with:
          name: tag-name-artifact
          path: tag_name.txt
